### PR TITLE
A much better fix for producing a commit hash when no files are staged.

### LINKED ISSUE #34: Repository with no staged changes does still produce a commit hash
Running `git-cm` on a repository with no staged changes does still go through the dialog and prints out the commit hash, but nothing gets added to the repository.
This should be fixed by adding a check that the repository contains staged files and if not, print an error message on stderr and terminate the process.

### PR DESCRIPTION
**Pull request by maksyms**
This PR fixes #34 .

I also took the time to better implement a few things:

1. Better separation of concerns: now `main.rs` does not need to know about the `git2` dependency - all git handling is hidden in `git.rs`
2. The check on whether the repository exists happens super-early, in `fn main()` in `main.rs`
3. Implemented a singleton pattern for finding Git repository, so once it is found once, there is no need to search for it again
4. Implemented correct identification of staged files by checking for all the statuses starting with `INDEX_*`

What I don't understand is why I need to use `once_cell::sync` instead of `once_cell::unsync`, as I cannot see any threads spawn here? Strange.

I think this is it, should work fine now. 👍

### CODE REVIEW

File: src/git.rs [hunk 1]
```diff
@@ -29,6 +29,42 @@ pub static DEFAULT_TYPES: Lazy<HashMap<&str, &str>> = Lazy::new(|| {
     m
 });
 
+// Singleton pattern
+pub fn get_repository(repo: &Path) -> Result<&Mutex<Repository>, Error> {
+    static REPO: OnceCell<Mutex<Repository>> = OnceCell::new();
```
Comment (SirWindfield) [inline src/git.rs:34]: Any specific reason why this has to be a `Mutex`? Wouldn't a `once_cell::Lazy` be enough to prevent multiple initializations?

The mutex should only be needed in a multi-threaded environment 🤔

Comment (SirWindfield) [inline src/git.rs:34]: Any specific reason why this has to be a `Mutex`? Wouldn't a `once_cell::Lazy` be enough to prevent multiple initializations?

The mutex should only be needed in a multi-threaded environment 🤔

Comment (SirWindfield) [reply src/git.rs:34]: I mean I'd keep it for now, whatever. It's not that the performance of those 0.1ms matter :) 
I am re-writing some stuff anyway to allow for #12. I can clean stuff like this up then.

Comment (maksyms) [reply src/git.rs:34]: No reason, just not sure how Lazy is different from this. I'll check and replace if it is doable, I don't mind.

I still don't get the reasoning for sync vs unsync. I know it is required by compiler as his is static, but why? Sync shouldn't be required in a single threaded app, and I don't see multithreading here.

Comment (maksyms) [reply src/git.rs:34]: Btw, Mutex is there because a sync OnceCell didn't compile without some sync primitive. Not sure Lazy is going to be any different, as it is essentially the same as OnceCell, but I'll check.

Comment (SirWindfield) [reply src/git.rs:34]: I actually have no clue why the sync version is needed here and not the unsync version. I never got unsync to work, so I guess I am missing some fundamental Rust knowledge here... Don't worry. We can keep it like this for now.

The rework does introduce structs to handle state so this won't be needed later on anyway.

Comment (SirWindfield) [reply src/git.rs:34]: @maksyms https://doc.rust-lang.org/reference/items/static-items.html
The first bullet point: static types has to be `Sync`. And since `Repository` doesn't implement it, you have to wrap it using `Mutex`.

Comment (maksyms) [reply src/git.rs:34]: Yep, I am aware of that. What I don't understand is "why". There is no first principle that dictates that must be the case.

I've done some reading, and it seems that Rust compiler is being very defensive and requires Sync for statics even if there is no multi-threading. Of course, figuring out whether the application is multi-threaded _is_ something the compiler can do. It is more difficult to do with re-entrability - so I accept the fact that the compiler cannot figure out whether the re-entrability requirements mean that the static needs to be protected with a sync primitive. Not how I'd do it in C/C++, but at least I'm closer to understanding the reason. 👍

Comment (SirWindfield) [reply src/git.rs:34]: I mean it would need code analysis that is beyond the borrow checker right now to determine if a function does thread out. It would have to analyze every single function body instead of just the signatures to determine the validity. You can't guarantee it if you call FFI.

So they probably just opted for making it Sync.

Comment (maksyms) [reply src/git.rs:34]: @SirWindfield, threading is implemented using `libpthreads` or similar libs and supported by kernels. It is trivial for Rust compiler to figure out whether any thread creation APIs are called or not. It probably chooses not to do so, and the safe thing to do when you don't check for calls to thread-creating APIs is to require Sync on static.

Comment (maksyms) [reply src/git.rs:34]: I _know_ using Mutex there is right in a Rust program. What I'm still puzzled about is _why_ - from the first principles, not just from the book. :) I think the latest parts of our discussion homed in on at least some of the reasons. :)

Comment (SirWindfield) [reply src/git.rs:34]: Ah ok I thought you didn't know _why_ you needed the Mutex. Makes sense.
> threading is implemented using libpthreads or similar libs and supported by kernels.

I didn't know that! TIL :)
